version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
